### ISSUE TITLE
大神可以把银联或者支付宝微信的官方sdk网址贴一下吗

### ISSUE THREAD

**Issue by hughdev** [poholo/alipay#1]
大神可以把银联或者支付宝微信的官方sdk网址贴一下吗

**Comment by poholo** [comment]
http://www.jianshu.com/p/97d38b00e53d

**Comment by poholo** [comment]
use 
https://github.com/poholo/LDSDKManager_IOS
https://github.com/poholo/MCAlipaySDK
https://github.com/poholo/SNWeChatSDK
